### ISSUE TITLE
Electron auto updater error

### ISSUE THREAD

**Issue by mpothier** [voyansi/ship#72]
Happens each time auto-updater is called to check for updates (Login view):
```
400 
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidArgument</Code><Message>Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified</Message><ArgumentName>Authorization</ArgumentName><ArgumentValue>token c2072be3910dc99cd37d459dd199870cdb23352f</ArgumentValue><RequestId>DYAQ6XBGBHDN1K4Y</RequestId><HostId>kneTZZHJgr09kxM9QG0vR5zxisxC6aZokKggCmYYQO/Ili92SXTI12iQqUBHLr5nUg2TIRCU4sY=</HostId></Error>"
Headers: {
  "status": "400",
  "x-amz-request-id": "DYAQ6XBGBHDN1K4Y",
  "x-amz-id-2": "kneTZZHJgr09kxM9QG0vR5zxisxC6aZokKggCmYYQO/Ili92SXTI12iQqUBHLr5nUg2TIRCU4sY=",
  "content-type": "application/xml",
  "server": "AmazonS3",
  "accept-ranges": "bytes",
  "via": "1.1 varnish, 1.1 varnish",
  "date": "Fri, 29 Jan 2021 20:07:14 GMT",
  "x-served-by": "cache-dca17777-DCA, cache-lga21920-LGA",
  "x-cache": "MISS, MISS",
  "x-cache-hits": "0, 0",
  "strict-transport-security": "max-age=31536000",
  "x-fastly-request-id": "cab15d5c79214fd483d18b390c267d5885b660b1"
}
```

Issue looks to be new for everyone using electron builder/auto updater for a private GitHub repo release:

https://github.com/electron-userland/electron-builder/issues/5595
https://github.com/electron-userland/electron-builder/pull/5594/commits/ddc37882f8a5613a7c3a45a788067ac2e773466f

Hopefully the commit above will be closed and we only need to update the the electron-builder version...

**Comment by paulkoeckdev** [comment]
Really needs to be fixed quickly!

**Comment by paulkoeckdev** [comment]
Doesn't this have to be fixed somehow else? What if people have the older version installed and can't update to the new one?

**Comment by mpothier** [comment]
> Doesn't this have to be fixed somehow else? What if people have the older version installed and can't update to the new one?

This is just an internal issue on our repo referencing to the core issue at https://github.com/electron-userland/electron-builder/issues/5595, I'd ask the question there
